/* Auto-generated by plan-to-sas-rtf for table 16.2.7.1 */

options nodate nonumber missing=' ' orientation=landscape;

%let xpt_path = D:\SAS_Data\TestD\development\test\input\adam\adae.xpt;
%let out_rtf  = D:\SAS_Data\TestD\development\test\output-20260408_181210\report\table_16.2.7.1.rtf;

libname src xport "&xpt_path";

data source_raw;
  set src.ADAE;
run;

data source_pop;
  set source_raw;
  where SAFFL = '是';
run;

proc sql noprint;
  select count(distinct USUBJID)
    into :n_pop trimmed
  from source_pop;
quit;

data listing_prep;
  set source_pop;
  length subject_key $200 hdr_line $400
         col_ae $20 col_socptterm $400 col_aestdtc $40 col_sequelae $80
         col_sevrel $200 col_actions $200 col_outcome $200
         col_sae $200 col_aedis $80;

  subject_key = catx('|', strip(TRTA), strip(USUBJID), strip(TRTSDTC));
  hdr_line = cats("组别 = ", strip(TRTA), ", 受试者编号 = ", strip(USUBJID), ", 给药日期 = ", strip(TRTSDTC));

  col_ae = strip(vvalue(AESEQ));
  col_socptterm = catx('^n', strip(AESOC), strip(AEDECOD), strip(AETERM));
  col_aestdtc = strip(AESTDTC);

  /* These columns are kept as placeholders because the current plan has no confirmed source. */
  col_sequelae = '';
  col_actions = '';
  col_outcome = '';

  col_sevrel = catx('^n', strip(AETOXGR), strip(AEREL));

  /* Keep the composite column structure, but only AESER is confirmed. */
  if not missing(AESER) then col_sae = cats(strip(AESER), '^n');
  else col_sae = '';

  col_aedis = strip(AEDIS);
run;

proc sort data=listing_prep out=listing_sorted;
  by subject_key AESTDTC AESEQ;
run;

ods escapechar='^';
ods rtf file="&out_rtf" style=journal bodytitle;

title1 j=c "清单 16.2.7.1: 所有不良事件清单";
title2 j=c "SS (N=&n_pop)";

footnote1 j=l "注：(1)A组为轻度肝功能损害(Child-Pugh A)受试者；B组为中度肝功能损害(Child-Pugh B)受试者；C组为肝功能正常健康受试者。";
footnote2 j=l "注：(2)编码字典: MedDRA xx.x。";

proc report data=listing_sorted nowd headline headskip split='|'
  style(report)={outputwidth=100% fontsize=9pt fontfamily='Arial'}
  style(column)={fontfamily='Arial' fontsize=9pt just=center asis=on}
  style(header)={fontfamily='Arial' fontsize=9pt fontweight=bold just=center};

  columns subject_key hdr_line col_ae col_socptterm col_aestdtc col_sequelae
          col_sevrel col_actions col_outcome col_sae col_aedis;

  define subject_key   / order noprint;
  define hdr_line      / order noprint;
  define col_ae        / display "AE";
  define col_socptterm / display "系统器官分类(SOC)|首选术语(PT)|不良事件名称";
  define col_aestdtc   / display "开始日期和时间";
  define col_sequelae  / display "有无后遗症";
  define col_sevrel    / display "严重程度|与试验药物关系";
  define col_actions   / display "对试验药物采取的措施|对不良事件采取的措施";
  define col_outcome   / display "转归|转归日期和时间";
  define col_sae       / display "是否为严重不良事件|符合的SAE标准";
  define col_aedis     / display "是否因此不良事件退出试验";

  compute before subject_key / style={just=l fontweight=bold};
    _trta = scan(subject_key, 1, '|');
    _usubjid = scan(subject_key, 2, '|');
    _trtsdtc = scan(subject_key, 3, '|');
    _hdr = cats("组别 = ", _trta, ", 受试者编号 = ", _usubjid, ", 给药日期 = ", _trtsdtc);
    line _hdr $400.;
  endcomp;

run;

ods rtf close;
title;
footnote;
